include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_late: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart